// Finite groups from generators and relations, for the hyperbolic tilings' closed surfaces.
// A surface where every tile is alike (a regular map) is its symmetry group: generated by R (a
// turn about a tile's middle, by one of its sides) and S (a turn about a corner, by one of the
// edges there), with (RS)² = 1, plus a few extra rules that make it finite. Coset enumeration
// (Todd–Coxeter) works the group out from the rules, as a table of where each element goes
// under each generator. Relators are written as in Conder & Dobcsányi's tables: letters R, S, T
// with powers (R^3, S^-2), brackets with powers ((RS^-2)^4), and commutators ([R,S^2], where
// [x,y] = x⁻¹y⁻¹xy).

// Generators are numbered by letter, each followed by its inverse: with letters "RST", R = 0,
// R⁻¹ = 1, S = 2, ... ("*" between letters, as in Conder's data files, is just a separator)
const inverse = (w) => w.slice().reverse().map((x) => x ^ 1);
const power = (w, n) => { const u = n < 0 ? inverse(w) : w; return Array.from({ length: Math.abs(n) }, () => u).flat(); };

// a relator in the tables' notation, as generator numbers
export function parseRelator(text, LETTERS = "RST") {
  const s = text.replace(/[\s*]+/g, "");
  let i = 0;
  const exponent = () => {
    if (s[i] !== "^") return 1;
    i++;
    const m = /^-?\d+/.exec(s.slice(i));
    if (!m) throw new Error(`bad power in ${text}`);
    i += m[0].length;
    return Number(m[0]);
  };
  const word = (stop) => {
    const out = [];
    while (i < s.length && !stop.includes(s[i])) {
      let atom;
      if (LETTERS.includes(s[i])) atom = [2 * LETTERS.indexOf(s[i++])];
      else if (s[i] === "(") { i++; atom = word(")"); if (s[i++] !== ")") throw new Error(`unclosed ( in ${text}`); }
      else if (s[i] === "[") {
        i++;
        const x = word(","); if (s[i++] !== ",") throw new Error(`bad commutator in ${text}`);
        const y = word("]"); if (s[i++] !== "]") throw new Error(`unclosed [ in ${text}`);
        atom = [...inverse(x), ...inverse(y), ...x, ...y];
      } else throw new Error(`unexpected ${s[i]} in ${text}`);
      out.push(...power(atom, exponent()));
    }
    return out;
  };
  const w = word("");
  if (i !== s.length) throw new Error(`leftover in ${text}`);
  return w;
}

// The group given by generators (count: how many letters, R, S, maybe T) and relators (generator
// number arrays): its elements, by coset enumeration on the trivial subgroup (HLT, with
// coincidences). Returns { size, gens }: each generator as a permutation of the elements.
// Throws if the enumeration grows past limit (an infinite or too-big group).
export function enumerate(count, relators, limit = 400000) {
  const G = 2 * count, inv = (x) => x ^ 1;
  const T = [], p = [];
  const fresh = () => {
    if (T.length >= limit) throw new Error(`more than ${limit} cosets`);
    T.push(new Int32Array(G).fill(-1));
    p.push(T.length - 1);
    return T.length - 1;
  };
  const find = (c) => { while (p[c] !== c) { p[c] = p[p[c]]; c = p[c]; } return c; };
  const queue = [];
  const merge = (k, l) => { k = find(k); l = find(l); if (k === l) return; if (k > l) [k, l] = [l, k]; p[l] = k; queue.push(l); };
  const coincidence = (a, b) => {
    merge(a, b);
    for (let qi = 0; qi < queue.length; qi++) {
      const e = queue[qi];
      for (let x = 0; x < G; x++) {
        const f = T[e][x];
        if (f < 0) continue;
        if (T[f][inv(x)] === e) T[f][inv(x)] = -1;
        const e1 = find(e), f1 = find(f);
        if (T[e1][x] >= 0) merge(f1, T[e1][x]);
        else if (T[f1][inv(x)] >= 0) merge(e1, T[f1][inv(x)]);
        else { T[e1][x] = f1; T[f1][inv(x)] = e1; }
      }
    }
    queue.length = 0;
  };
  // trace relator w from coset c both ways, defining new cosets to close it up
  const scan = (c, w) => {
    let f = c, b = c, i = 0, j = w.length - 1;
    for (;;) {
      while (i <= j && T[f][w[i]] >= 0) f = T[f][w[i++]];
      if (i > j) { if (find(f) !== find(b)) coincidence(f, b); return; }
      while (j >= i && T[b][inv(w[j])] >= 0) b = T[b][inv(w[j--])];
      if (j < i) { coincidence(f, b); return; }
      if (i === j) { T[f][w[i]] = b; T[b][inv(w[i])] = f; return; }
      const n = fresh(); T[f][w[i]] = n; T[n][inv(w[i])] = f;
    }
  };
  fresh();
  for (let c = 0; c < T.length; c++) {
    for (const r of relators) { if (find(c) !== c) break; scan(c, r); }
    if (find(c) !== c) continue;
    for (let x = 0; x < G; x++) if (T[c][x] < 0) { const n = fresh(); T[c][x] = n; T[n][inv(x)] = c; }
  }
  const live = [...T.keys()].filter((c) => find(c) === c), index = new Map(live.map((c, i) => [c, i]));
  const gens = Array.from({ length: count }, (_, g) => live.map((c) => index.get(find(T[c][2 * g]))));
  return { size: live.length, gens, peak: T.length }; // (peak: the most cosets it needed on the way)
}

// the order of a permutation: the least common multiple of its cycles' lengths
export function permOrder(perm) {
  const seen = new Uint8Array(perm.length), gcd = (x, y) => (y ? gcd(y, x % y) : x);
  let L = 1;
  for (let i = 0; i < perm.length; i++) {
    if (seen[i]) continue;
    let n = 0;
    for (let j = i; !seen[j]; j = perm[j]) { seen[j] = 1; n++; }
    L = (L * n) / gcd(L, n);
  }
  return L;
}
export const composePerm = (p1, p2) => p1.map((_, i) => p2[p1[i]]); // p1, then p2

// a regular map's group from its table row ({ kind, relators }): orientable maps (reflexible or
// chiral) are their turning group ⟨R, S | (RS)², ...⟩; non-orientable ones add the reflection T,
// ⟨R, S, T | T², (RT)², (TS)², (RS)², ...⟩
export function mapGroup(row, limit) {
  const base = row.kind === "nonorientable" ? ["T^2", "(RT)^2", "(TS)^2", "(RS)^2"] : ["(RS)^2"];
  return enumerate(row.kind === "nonorientable" ? 3 : 2, [...base, ...row.relators].map((r) => parseRelator(r)), limit);
}

// a word (in the group's letters) as a permutation of its elements, from its generators'
export function wordPerm(gens, word) {
  let perm = gens[0].map((_, i) => i);
  const invs = gens.map((g) => { const out = new Array(g.length); g.forEach((j, i) => (out[j] = i)); return out; });
  for (const x of word) perm = composePerm(perm, x & 1 ? invs[x >> 1] : gens[x >> 1]);
  return perm;
}
// how many elements a set of permutations of a group's elements generates (in the group's
// action on itself, that's the orbit of one element)
export function generatedSize(perms) {
  const seen = new Uint8Array(perms[0].length), stack = [0];
  seen[0] = 1;
  let n = 1;
  while (stack.length) {
    const i = stack.pop();
    for (const p of perms) if (!seen[p[i]]) { seen[p[i]] = 1; n++; stack.push(p[i]); }
  }
  return n;
}
